steps:
- name: 'node:20.12.1'
  entrypoint: 'npm'
  args: ['ci']
- name: node:20.12.1
  entrypoint: npx
  args: ['bundage', 'bfn', 'dev/main', 'main_bin', '-t', 'bin']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/phading-dev/user-session-cron-job:latest', '-f', 'dev/Dockerfile', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/phading-dev/user-session-cron-job:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'dev/service.yaml']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=phading-cluster'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
