apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-session-cron-job
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  timezone: "Pacific/Pitcairn"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: user-session-cron-account
          containers:
          - name: user-session-cron-job
            image: gcr.io/phading-dev/user-session-cron-job:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
