apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-session-cron-job
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  timeZone: "Pacific/Pitcairn"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: user-session-cron-account
          containers:
          - name: user-session-cron-job
            image: gcr.io/phading-prod/user-session-cron-job:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "100m"
                memory: "128Mi"
          restartPolicy: OnFailure
